### ISSUE TITLE
Error on Server Name

### ISSUE THREAD

**Issue by ernestocd** [khibma/ArcGISAdministrationToolkit#14]
I receive this error on the tool when trying to connect to a server in the tool:
I am using our qualified host name, which supports both HTTP and HTTPS.
Any ideas why this stopped working?
`Close WindowERROR 
updateParameters Execution Error: Runtime error Traceback (most recent call last): File "C:\Users\ecarreras\Documents\Tools\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 4, in File "C:\Users\ecarreras\Documents\Tools\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 23, in updateParameters File "C:\Users\ecarreras\Documents\Tools\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 74, in getServiceList File "C:\Users\ecarreras\Documents\Tools\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 55, in gentoken File "C:\Python27\ArcGIS10.4\Lib\urllib.py", line 89, in urlopen return opener.open(url, data) File "C:\Python27\ArcGIS10.4\Lib\urllib.py", line 215, in open return getattr(self, name)(url, data) File "C:\Python27\ArcGIS10.4\Lib\urllib.py", line 350, in open_http h.endheaders(data) File "C:\Python27\ArcGIS10.4\Lib\httplib.py", line 1049, in endheaders self._send_output(message_body) File "C:\Python27\ArcGIS10.4\Lib\httplib.py", line 893, in _send_output self.send(msg) File "C:\Python27\ArcGIS10.4\Lib\httplib.py", line 855, in send self.connect() File "C:\Python27\ArcGIS10.4\Lib\httplib.py", line 832, in connect self.timeout, self.source_address) File "C:\Python27\ArcGIS10.4\Lib\socket.py", line 557, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): IOError: [Errno socket error] [Errno 11001] getaddrinfo failed `

**Comment by khibma** [comment]
Hi, I'm sorry I'm not sure what the problem is. It sounds more like the machine with your Python script cannot talk to the Server machine. Meaning, it doesnt sound like a python/code problem. It sounds like the two machines cant communicate. 
That or the hostname you're providing might not be right?
